# Generated by Django 5.0.3 on 2024-03-15 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_studentclass_user_dob_user_image_user_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentclass',
            old_name='cls',
            new_name='cls_name',
        ),
    ]
